language: python
services:
  - docker
install:
  - make deps
script:
  - make test
  - make docker_build
after_success:
  - make docker_push
deploy:
  provider: heroku
  api_key:
    secure: "${HEROKU_API_KEY}"
